name: Deploy Python App

on:
  push:
    branches:
      - main
      - dev
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to VM
      env:
        BRANCH_NAME: ${{ github.ref_name }}
      run: |
        ssh -i ~/.ssh/id_ed25519 ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << EOF
          cd ~/ci-cd-pipeline || git clone https://github.com/NithishBlaze/ci-cd-pipeline.git ~/ci-cd-pipeline
          cd ~/ci-cd-pipeline

          git fetch origin
          git checkout \$BRANCH_NAME
          git pull origin \$BRANCH_NAME

          python3 -m venv myvenv
          source myvenv/bin/activate

          pip install -r requirements.txt

          python app.py
        EOF
