name: Deploy Python App

on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Setup SSH
          run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_ed25519
                chmod 600 ~/.ssh/id_ed25519
                ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts || exit 0

        - name: Deploy to VM
          run: |
            ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
                cd ~/work/ci-cd-pipeline || git clone https://github.com/NithishBlaze/ci-cd-pipeline.git
                cd work/ci-cd-pipeline

                git pull origin ${{github.ref_name}}

                source myvenv/bin/activate || python3 -m venv myvenv && source myvenv/bin/activate

                pip install -r requirements.txt

                python app.py
            EOF
